#!/usr/bin/env bash

# ------------------------------------------------------------------
# [jhwshin] _power-management (desktop)
#
#   Description:
#       power management using xidlehook
#           dim, lockscreen, display off, suspend
#
#   Dependencies:
#       - xidlehook
#       - lockscreen (i3lock-color)
#       - caffeine-ng ('--not-when-audio' currently doesn't work properly)
# ------------------------------------------------------------------

DISPLAY_1="DP-4"
DISPLAY_2="HDMI-0"
LOCKSCREEN_CMD="lockscreen"

xidlehook \
    --not-when-audio \
    --timer 300     "xrandr --output ${DISPLAY_1} --brightness .5 --output ${DISPLAY_2} --brightness .5" \
                    "xrandr --output ${DISPLAY_1} --brightness 1 --output ${DISPLAY_2} --brightness 1" \
    --timer 300     "${LOCKSCREEN_CMD}" "xrandr --output ${DISPLAY_1} --brightness 1 --output ${DISPLAY_2} --brightness 1" \
    --timer 300     "xrandr --output ${DISPLAY_1} --brightness 1 --output ${DISPLAY_2} --brightness 1; xset dpms force standby" "" \
    --timer 300     "systemctl suspend" ""